fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Auth\AuthBundle\Entity\User
    service:
            mailer: fos_user.mailer.twig_swift
    registration:
            confirmation:
                enabled:    true
                from_email:
                    address:        test@test.com
                    sender_name:    Test Registration
                template: AuthBundle:Default:confirmation.email.html.twig
            form:
                type: auth_user_registration