parameters:
#    auth.example.class: Auth\AuthBundle\Example

services:
    auth_user.registration.form.type:
        class:  Auth\AuthBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: auth_user_registration }

    auth_user.registration:
        class: Auth\AuthBundle\EventListener\RegistrationListener
        arguments:
            - @router
            - @doctrine.orm.entity_manager
            - @fos_user.user_manager
            - {'referal.cookie.name': %referal.cookie.name%}
        tags:
            - { name: kernel.event_subscriber }

    referal.listener:
            class:     Auth\AuthBundle\EventListener\ReferalListener
            arguments:
                - @doctrine.orm.entity_manager
                - @router
                - @fos_user.user_manager
                - {'referal.param.name': %referal.param.name%, 'referal.cookie.name': %referal.cookie.name%}
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -1 }
                - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 255 }